name: ltf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - appdirs==1.4.4
    - blessed==1.20.0
    - cerberus==1.3.2
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.7
    - contourpy==1.2.1
    - cycler==0.12.1
    - cytoolz==0.11.0
    - docker-pycreds==0.4.0
    - easydict==1.13
    - filelock==3.9.0
    - fonttools==4.50.0
    - fsspec==2024.3.1
    - funcy==1.15
    - gin-config==0.3.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gpustat==1.1.1
    - huggingface-hub==0.22.2
    - idna==3.4
    - importlib-resources==6.4.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - markupsafe==2.1.3
    - matplotlib==3.8.4
    - mpmath==1.3.0
    - munch==2.5.0
    - networkx==3.2.1
    - numpy==1.24.1
    - nvidia-ml-py==12.535.133
    - packaging==24.0
    - pandas==2.2.1
    - pathtools==0.1.2
    - pillow==10.2.0
    - promise==2.3
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytorch-warmup==0.1.1
    - pytz==2024.1
    - pyyaml==5.4
    - quinine==0.3.0
    - regex==2023.12.25
    - requests==2.28.1
    - sacremoses==0.1.1
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - sentry-sdk==1.44.0
    - setproctitle==1.3.3
    - shortuuid==1.0.13
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.12
    - termcolor==2.3.0
    - threadpoolctl==3.4.0
    - tokenizers==0.15.2
    - toolz==0.12.1
    - toposort==1.5
    # - torch==2.1.2+cu121
    - torch-ema==0.3
    # - torchaudio==2.1.2+cu121
    # - torchvision==0.16.2+cu121
    - tqdm==4.66.2
    - triton==2.1.0
    - typing-extensions==4.8.0
    - tzdata==2024.1
    - urllib3==1.26.13
    - wandb==0.14.0
    - wcwidth==0.2.13
    - xgboost==2.0.3
    - yaspin==3.0.2
    - zipp==3.18.1

